"""monitorss

Revision ID: bb6647b1942d
Revises: 
Create Date: 2018-12-04 15:30:38.362319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb6647b1942d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=256), nullable=True),
    sa.Column('cpu_count', sa.Integer(), nullable=True),
    sa.Column('cpu_count_logical', sa.Integer(), nullable=True),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('mem_total', sa.Float(), nullable=True),
    sa.Column('mem_percent', sa.Float(), nullable=True),
    sa.Column('disks', sa.String(length=1024), nullable=True),
    sa.Column('insert_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitor_insert_time'), 'monitor', ['insert_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitor_insert_time'), table_name='monitor')
    op.drop_table('monitor')
    # ### end Alembic commands ###
