"""monitors4

Revision ID: f25e0950657b
Revises: bb6647b1942d
Create Date: 2018-12-04 16:14:57.318445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f25e0950657b'
down_revision = 'bb6647b1942d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitor', sa.Column('ip', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitor', 'ip')
    # ### end Alembic commands ###
